### ISSUE TITLE
"Time data 'None' " Error going from 2.6 to either 3.0 or 3.1

### ISSUE THREAD

**Issue by MihleTX** [briis/meteobridge#14] opened 2021-11-23 15:30 UTC
I updated yesterday trying to go from 2.6 to 3.0.  I followed the instructions exactly updating, then restarting, deleting integration, then adding integration.  All of those steps were successful.

While the integration is successfully completed, I immediately get the following error:
Retrying setup: time data 'None' does not match format '%Y%m%d%H%M%S'

I rolled back to 2.6 and everything was up and running again (yesterday)

Seeing the 3.1 update, I decided to try it all again, this time not double tasking so I was more focused, realizing the update notes did not cover this issue, but considering user error on my side.

Same process to update, restart, delete, add integration.  Same outcome.

Are my steps in the wrong order?  I dont have logs enabled yet, but I can get them going if it will help.  My plan was to roll back to 2.6 again at this point.

Thanks

**Comment by briis** [comment] 2021-11-23 19:03
You are not doing anything wrong. The error comes when I am trying to convert one of the timestrings from Meteobridge into a Datetime that HA understands, and for some reason that fails - which it shouldn't.

I will put in some error logging and handling, so that we can figure where exactly it goes wrong. Tomorrow I will post a 3.0.2 that should work, but will also be able to tell me where the error is. 

Is there anything in the Home Assistant log file?

**Comment by MihleTX** [comment] 2021-11-23 19:46
I did not see anything in my logs no - but I could try and re-create the update if you need me to.

Otherwise I will certainly do the update for tomorrow.  Do you want me to roll back to 2.6 before trying 3.0.2 or do you want me to just try and move from 3.0.1 to 3.0.2??

**Comment by briis** [comment] 2021-11-23 19:47
Just stay on the version you are on.

**Comment by briis** [comment] 2021-11-23 21:05
So I managed to do this before bedtime. 3.0.2 is released. 

Enable the debug log before you upgrade by editing `configuration.yaml` and add this is the right place:
```yaml
logger:
  default: error
  logs:
    custom_components.meteobridge: debug
```

Then do the upgrade to 3.0.2  and after Home Assistant restart, please check the log file for errors and post them here.

**Comment by MihleTX** [comment] 2021-11-23 21:37
Still failing - I am getting this in logs:

Logger: pymeteobridgedata.helpers
Source: /usr/local/lib/python3.9/site-packages/pymeteobridgedata/helpers.py:98
First occurred: 3:20:15 PM (34 occurrences)
Last logged: 3:36:24 PM

An error occured converting MB Time. Input Value is : None and Error message is time data 'None' does not match format '%Y%m%d%H%M%S'

**Comment by briis** [comment] 2021-11-24 05:54
That is as expected, as I did not fix the error, but you should be getting some data now, without the Integration crashing?

Could you try and copy the below string to a webbrowser, changing USERNAME to the username of your Meteobridge, PASSWORD to the password you use and IP_ADDRESS to the ip address of the Meteobridge device. Then post the result of that here.

`http://USERNAME:PASSWORD@IP_ADDRESS/cgi-bin/template.cgi?template=[th0temp-dmintime=utc:dmin
];[th0temp-dmaxtime=utc:dmax];[th0temp-mmintime=utc:mmin];[th0temp-mmaxtime=utc:mmax];[th0temp-ymintime=utc:ymin];[th0temp-ymaxtime=utc:ymax]
`

**Comment by WouterKr** [comment] 2021-11-24 06:05
Hi, 

Having the same issue I tried the above link and the result in my case is:

20211124060216;20211124060204;20211124060216;20211124060204;20210213071623;20210617133831

Hope this wil help.

Regards,
Wouter

**Comment by briis** [comment] 2021-11-24 06:09
Thanks. Data looks initially fine, but I will try and run these through the converter and see why it fails.

**Comment by briis** [comment] 2021-11-24 06:41
Just tested all the data you send and no errors are thrown. So it must be that sometimes the request does not return the expected data. 

This functions takes the Date and Time of the Temperature Min and Max for Day, Month and Year and converts it to something Home Assistant can work with.
I have now added an extra check so that the function will not fail, but I am still puzzled why you get errors. Personally I have never seen this error.

Once 3.0.3 is released, could you occasionally check the below sensors to see if it has the attribute `measure_time`, as this is the attribute that gets filled with the value from this.

```yaml
- sensor.meteobridge_air_temperature_dmin
- sensor.meteobridge_air_temperature_dmax
- sensor.meteobridge_air_temperature_mmin
- sensor.meteobridge_air_temperature_mmax
- sensor.meteobridge_air_temperature_ymin
- sensor.meteobridge_air_temperature_ymax
````

**Comment by WouterKr** [comment] 2021-11-24 06:58
Thanks and sure I will look at the sensors to check whether the measure_time is filled and let you know.

**Comment by MihleTX** [comment] 2021-11-24 07:48
I just popped the link in my system here and this is what I got:
20211124073235;20211124060001;20211119131007;20211117202138;ymin;ymax

M

**Comment by briis** [comment] 2021-11-24 07:58
Thanks @MihleTX 
This shows that you are not getting any data for the Yearly Min and Max times. I am not sure why Meteobridge does not have that data. If it has daily and monthly data, it should also have yearly data. 

The best thing I can do is that from the next release I will ensure the error does not popup, and as I wrote to @WouterKr please check the sensors above for their values and attributes regularly, just to have an idea how often this happens.

**Comment by MihleTX** [comment] 2021-11-24 08:53
Update - Well - I will tell you that I made one change in meteobridge and now everything works for me.  

I went to the "Weatherstation" "Primary Station" panel:  I checked these two boxes:

Apply longitude/latitude/altitude/timezone/rain season settings of Meteobridge
Transfer rain totals for day, month and year from console to Meteobridge

Upon hitting save, meteobridge restarted the logger.  

I did perform a HA restart after (not sure if that mattered)

Voila - the integration has no errors.  I see the data flowing in, and now I am just re-mapping the sensors to all my custom lovelace cards.

If things change- I will update here, but for me - that worked.

**Comment by briis** [comment] 2021-11-24 09:39
Perfect, thanks for letting me know. I will put that in the discussion area, so others can find the same info.

One question: Was your station installed this calendar year?

**Comment by MihleTX** [comment] 2021-11-24 09:56
technically no the station has been around for 10+ years - but I did finally get the latest meteobridge software update within the last year.

**Comment by briis** [comment] 2021-11-24 10:24
Ok, thanks. I was just wondering why the Yearly Data was not on the Meteobridge, but I guess that is a question for the creators of that. But glad you found a solution.

**Comment by MihleTX** [comment] 2021-11-24 10:25
new update.  sorry - the integration does not show errors, and the data is updating on the sensors.  But I am throwing the same error in the logs:
2021-11-24 04:25:01 ERROR (MainThread) [pymeteobridgedata.helpers] An error occured converting MB Time. Input Value is : None and Error message is time data 'None' does not match format '%Y%m%d%H%M%S'

**Comment by briis** [comment] 2021-11-24 10:40
The error and success are two different things. The success is just a confirmation that the system has received new data in general from the Meteobridge. (You can turn off the Debug again in the configuration.yaml)

If you go to developer tools and look and find the sensors I mention above, can you check the attribute values of the `measure_time`. I will asume it shows a date for the Day and Month sensors and None for the Year sensors.

So I think you have the same error as @WouterKr as this seems to be a dynamic thing, sometimes you get the data and sometime you don't.

**Comment by MihleTX** [comment] 2021-11-24 10:45
> If you go to developer tools and look and find the sensors I mention above, can you check the attribute values of the measure_time. I will asume it shows a date for the Day and Month sensors and None for the Year sensors.

Yep - still getting this:
20211124080555;20211124060001;20211119131007;20211117202138;ymin;ymax

**Comment by briis** [comment] 2021-11-24 10:55
Exactly. 

Could you try this string instead, I just want to check if you get values and not the time or both.

`http://USERNAME:PASSWORD@IP_ADDRESS/cgi-bin/template.cgi?template=[th0temp-ymin:ymin];[th0temp-ymax:ymax];[th0temp-ymintime=utc:ymintime];[th0temp-ymaxtime:ymaxtime]`

**Comment by MihleTX** [comment] 2021-11-24 10:57
-17.8;38.4;ymintime;ymaxtime

**Comment by briis** [comment] 2021-11-24 11:01
So you get the data but not the time of the data - that must be an error in your Meteobridge Database.
Try and login to the Meteobridge device and click on *Live Data* in the top and then on *Min/Max Data*.
If you the hover the mouse over the outdoor temperature for the year, do you see a Date?

**Comment by MihleTX** [comment] 2021-11-24 11:05
There is no date for outside temp year and all.  I will have to look into that....

**Comment by MihleTX** [comment] 2021-11-24 11:07
I just Erased the data - now everything is re-populated across all the live data, with dates, and no errors thrown in HA.

**Comment by briis** [comment] 2021-11-24 11:07
Yes, that is the problem - I have both a Local date and a UTC date when doing that.
So the Issue is with Meteobridge and not with this integration. Try and ask in the [Forum](https://forum.meteohub.de/) they tend to be very responsive.

**Comment by MihleTX** [comment] 2021-11-24 11:08
Yep you are right - sorry about the runaround there.

**Comment by briis** [comment] 2021-11-24 11:08
Wonderful. Thanks

@WouterKr Could you also have a look in Meteobridge to see if you have the same issue?

**Comment by briis** [comment] 2021-11-24 11:09
And no worries @MihleTX, how would you (and I) know where the error came from. I am just glad we found it.

**Comment by WouterKr** [comment] 2021-11-24 11:51
Just checked meteobridge min/max values. Hovering over the data I can see that they all have a time date .

**Comment by briis** [comment] 2021-11-24 15:05
There must be something with your Meteobridge device. In @MihleTX case it was always the Yearly Data, and with you it is day and month data. It should not take 1-2 min for the Meteobridge device to calculate the Min and Max values. All the data I pull from it takes 0.2ms to compute.

Did you try and Erase the data like @MihleTX did? I am not sure though how he erased it. It seems to repopulate again, so no data loss. That might fix a corrupt data entry?

**Comment by MihleTX** [comment] 2021-11-24 15:07
Off of "live data" tab - you can click Erase.  It does eliminate your history in Meteobridge, but for me that did not matter that much.

**Comment by WouterKr** [comment] 2021-11-24 16:29
I agree. Looking at my meteobridge it seemed to run fine but on the hour some stuck (backup?) process seemed to prevent access to the meteobridge. Rebooted the meteobridge I have not seen the error in the last hour.  Seems all fine now.......
Btw. did not erase the data like @MihleTX did.

**Comment by briis** [comment] 2021-11-24 16:31
Fantastic. I will close this now. Just reopen if this happens again.

**Closed by briis** 2021-11-24 16:31 UTC
Labels: bug
